### ISSUE TITLE
about pre_process.py

### ISSUE THREAD

**Issue by lymgoforit** [foamliu/Listen-Attend-and-Spell#2]
hi,When I run pre_process.py, the following error occurs：

$ python pre_process.py

getting train data...
Traceback (most recent call last):
  File "pre_process.py", line 64, in <module>
    data['train'] = get_data('train')
  File "pre_process.py", line 27, in get_data
    dirs = [os.path.join(folder, d) for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d))]
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_aishell/wav/train'

can you help me?thank you.

**Comment by mdhasanai** [comment]
Recently I run this script and i also got this problem. The error is occurred because when you download the dataset and extract "data_aishell" tar file by running "extract.py" file but there are remaining some files that also need to be extract before you run "pre_process.py" script.
Here is the solution.

Just run this script
```python
import os
import tarfile
names = []
for root, dirs, files in os.walk("./data/data_aishell/wav/", topdown=False):
    for name in files:
        names.append(os.path.join(root, name))
for n in names:
    extract(n)
```
